=== AlehDumava/training/MyThirdProject/src/MyXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MyXMLSchema" 
xmlns:tns="http://www.example.org/MyXMLSchema" elementFormDefault="qualified">
	<element name="dimond_fund">
		<complexType>
			<sequence>
				<element name="stone" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="name" type="string" />
							<element name="preciousness">
								<simpleType>
									<restriction base="string">
										<enumeration value="Полудрагоценный"/>
										<enumeration value="Драгоценный"/>
									</restriction>
								</simpleType>
							</element>
							<element name="origin" type="string"/>
							<element name="visual_parameters">	
								<complexType>
									<sequence>
										<element name="color">
											<simpleType>
												<restriction base="string">
													<enumeration value="Бесцветный"/>
													<enumeration value="Синий"/>
													<enumeration value="Красный"/>
													<enumeration value="Зеленый"/>
												</restriction>
											</simpleType>
										</element>
										<element name="opacity" minOccurs="0">
											<simpleType>
												<restriction base="byte">
													<minInclusive value="0"/>
													<maxInclusive value="100"/>
												</restriction>
											</simpleType>
										</element>
										<element name="way_faceting" minOccurs="1">
											<simpleType>
												<restriction base="byte">
													<minInclusive value="4"/>
													<maxInclusive value="15"/>
												</restriction>
											</simpleType>
										</element>
									</sequence>
								</complexType>
							</element>
							<element name="value" minOccurs="1">
								<simpleType>
									<restriction base="integer">
										<minInclusive value="1"/>
										<maxInclusive value="100"/>
									</restriction>
								</simpleType>
							</element>
						</sequence>
						<attribute name="id" type="string" use="required"/>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== AlehDumava/training/MyThirdProject/MyXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<dimond_fund xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/MyXMLSchema" 
	xsi:schemaLocation="http://www.example.org/MyXML MyXMLSchema.xsd">
	<stone id="Stone #1">
		<name>Бриллиант</name>>
		<preciousness>Драгоценный</preciousness>>
		<origin>Африка</origin>
		<visual_parameters>
			<color>Бесцветный</color>
			<opacity>100</opacity>
			<way_faceting>15</way_faceting>
		</visual_parameters>
		<value>5</value>
	</stone>
	<stone id="Stone #2">
		<name>Сапфир</name>>
		<preciousness>Драгоценный</preciousness>>
		<origin>Африка</origin>
		<visual_parameters>
			<color>Синий</color>
			<opacity>95</opacity>
			<way_faceting>5</way_faceting>
		</visual_parameters>
		<value>7</value>
	</stone>
	<stone id="Stone #3">
		<name>Рубин</name>>
		<preciousness>Драгоценный</preciousness>>
		<origin>Зимбабве</origin>
		<visual_parameters>
			<color>Красный</color>
			<opacity>100</opacity>
			<way_faceting>13</way_faceting>
		</visual_parameters>
		<value>3</value>
	</stone>
	<stone id="Stone #4">
		<name>Топаз</name>>
		<preciousness>Полудрагоценный</preciousness>>
		<origin>Бразилия</origin>
		<visual_parameters>
			<color>Синий</color>
			<opacity>99</opacity>
			<way_faceting>12</way_faceting>
		</visual_parameters>
		<value>3</value>
	</stone>
	<stone id="Stone #5">
		<name>Опал</name>>
		<preciousness>Полудрагоценный</preciousness>>
		<origin>Австралия</origin>
		<visual_parameters>
			<color>Зеленый</color>
			<opacity>60</opacity>
			<way_faceting>14</way_faceting>
		</visual_parameters>
		<value>6</value>
	</stone>
</dimond_fund>
